; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = src

[env:hover_ble]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags = 
	-D ADAPTER_MODE=0
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-Os
	-ffunction-sections
	-fdata-sections
extra_scripts = pre:version_git.py
lib_deps = 
	h2zero/NimBLE-Arduino @ ^1.4.1
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

[env:hover_wifi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags = 
	-D ADAPTER_MODE=1
	-D CORE_DEBUG_LEVEL=3
	-D BOARD_HAS_PSRAM
	-Os
	-ffunction-sections
	-fdata-sections
lib_deps = h2zero/NimBLE-Arduino@^2.5.0
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
