; ============================================================
; ESP32 平衡车中间控制器 — PlatformIO 配置
; ============================================================
[platformio]
src_dir = src

; ===================== BLE 模式 =====================
[env:hover_ble]
platform    = espressif32
board       = esp32-s3-devkitc-1
framework   = arduino

build_flags =
    -D ADAPTER_MODE=0
    -D CORE_DEBUG_LEVEL=3       ; 开启详细日志
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    ESP32 BLE Arduino

monitor_speed = 115200
upload_speed  = 921600

; 上传后自动打开串口监视器
monitor_filters = esp32_exception_decoder

; ===================== WiFi 模式 =====================
[env:hover_wifi]
platform    = espressif32
board       = esp32-s3-devkitc-1
framework   = arduino

build_flags =
    -D ADAPTER_MODE=1
    -D CORE_DEBUG_LEVEL=3

lib_deps =

monitor_speed = 115200
upload_speed  = 921600
monitor_filters = esp32_exception_decoder
